In [80]:
x = 5
x

5

In [81]:
x+2
x-2
x*2
x**2
x/float(2)
x**2


25

In [82]:
# help(str)
int(6)
float(7)
type(bool("True"))

bool

In [83]:
my_string = 'thisisawesome'
my_string
my_string*2
my_string + '_day'
'sis' in my_string
my_string[3]
my_string[1:3]

'hi'

In [84]:
a = 'is'
b  = 'nice'
my_list = ['my', 'list', a, b]
my_list.append(7)
my_list.append(True)
my_list.append('is')
my_list.__len__()
my_list[-2]
print(my_list)
print(my_list[1:3])
print(my_list[:3])
print(my_list[1:])
print(my_list[:])
my_list1 = my_list[1:5]
print(my_list1)

my_list2 = [[4,5,6,7], [3,6,7,8]]
print(my_list2)
print(my_list2[1][:3])
for e in my_list:
    print(e)
my_list.count('is')
del(my_list[1:3])
my_list



['my', 'list', 'is', 'nice', 7, True, 'is']
['list', 'is']
['my', 'list', 'is']
['list', 'is', 'nice', 7, True, 'is']
['my', 'list', 'is', 'nice', 7, True, 'is']
['list', 'is', 'nice', 7]
[[4, 5, 6, 7], [3, 6, 7, 8]]
[3, 6, 7]
my
list
is
nice
7
True
is


['my', 'nice', 7, True, 'is']

In [85]:
import math
print("Its a math! IT has type {}".format(type(math)))

Its a math! IT has type <class 'module'>


In [86]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [87]:
print(math.pi)

3.141592653589793


In [88]:
math.log(32, 2)

5.0

In [89]:
import numpy as np

In [90]:
rolls = np.random.randint(low=1, high=10, size=10)
rolls

array([4, 4, 4, 9, 9, 6, 8, 3, 4, 1], dtype=int32)

In [91]:
type(rolls)

numpy.ndarray

In [92]:
dir(rolls)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [93]:
m = rolls.mean()
print(m)

5.2


In [94]:
rolls.tolist()

[4, 4, 4, 9, 9, 6, 8, 3, 4, 1]

In [95]:
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])

    Return a flattened array.

    Refer to `numpy.ravel` for full documentation.

    See Also
    --------
    numpy.ravel : equivalent function

    ndarray.flat : a flat iterator on the array.



In [96]:
type(rolls)

numpy.ndarray

In [97]:
rolls.tolist()+10

TypeError: can only concatenate list (not "int") to list

In [ ]:
rolls + 10

array([18, 13, 19, 16, 12, 12, 19, 13, 14, 11], dtype=int32)

In [ ]:
rolls <= 3

array([False,  True, False, False,  True,  True, False,  True, False,
        True])

In [ ]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = np.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [ ]:

raw, col = x.shape
print(raw, ",", col)

2 , 3


In [ ]:
x[1,-1]

np.int64(6)

In [ ]:
xlist[1, -1]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
xlist[1][-1]

6