In [611]:
import numpy as np
from scipy.spatial.distance import cdist

In [612]:
data = np.array([[2.50, 3.17],
       [2.50, 3.17],
       [2.50, 3.17],
       [7.50, 8.17],
       [7.50, 8.17],
       [7.50, 8.17]])

In [613]:
point = np.array([2.0, 3.0])

In [614]:
shifted_points = np.copy(data)
print(shifted_points)
new_points = np.zeros_like(shifted_points)
new_points

[[2.50 3.17]
 [2.50 3.17]
 [2.50 3.17]
 [7.50 8.17]
 [7.50 8.17]
 [7.50 8.17]]


array([[0.00, 0.00],
       [0.00, 0.00],
       [0.00, 0.00],
       [0.00, 0.00],
       [0.00, 0.00],
       [0.00, 0.00]])

In [615]:
h = 1.5

In [616]:
distances = cdist([point], data, metric='euclidean')[0]
print(distances)
type(distances)


[0.53 0.53 0.53 7.55 7.55 7.55]


numpy.ndarray

In [617]:
kernel_values = np.exp(-0.5*(distances/h)**2)/(h*np.sqrt(2*np.pi))
print(kernel_values)
type(kernel_values)

[0.25 0.25 0.25 0.00 0.00 0.00]


numpy.ndarray

In [618]:
kernel_values_reshaped = kernel_values.reshape(len(kernel_values),1)
kernel_values_reshaped

array([[0.25],
       [0.25],
       [0.25],
       [0.00],
       [0.00],
       [0.00]])

In [619]:
weighted_data = np.multiply(data, kernel_values_reshaped)
weighted_data

array([[0.62, 0.79],
       [0.62, 0.79],
       [0.62, 0.79],
       [0.00, 0.00],
       [0.00, 0.00],
       [0.00, 0.00]])

In [620]:
weighted_data_sum = np.sum(weighted_data, axis=0)
print(weighted_data_sum)
kernel_values_sum = np.sum(kernel_values)
print(kernel_values_sum)

[1.87 2.38]
0.7499372381552979


In [621]:
mean_shift = np.divide(weighted_data_sum, kernel_values_sum)
print(mean_shift)

[2.50 3.17]


In [622]:
np.add(mean_shift, point)

array([4.50, 6.17])

In [623]:
def calculate_mean_shift_vector(point, data, h):
    distances = cdist([point], data, metric='euclidean')[0]
    kernel_values = np.exp(-0.5*(distances/h)**2)/(h*np.sqrt(2*np.pi))
    kernel_values_reshaped = kernel_values.reshape(len(kernel_values),1)
    # print("kernel_value_shaped ", kernel_values_reshaped)
    weighted_data = np.multiply(data, kernel_values_reshaped)
    # print("weighted_data ",weighted_data)
    weighted_data_sum = np.sum(weighted_data, axis=0)
    kernel_values_sum = np.sum(kernel_values)
    mean_shift = np.divide(weighted_data_sum, kernel_values_sum)
    return mean_shift



In [624]:
def mean_shift(data):
    shifted_points = np.copy(data)
    tolerance = 1e-3
    for iteration in range(1, 10):
        max_shift = 0
        new_points = np.zeros_like(shifted_points)
        for i in range(len(shifted_points)):
            mean_shift_vector = calculate_mean_shift_vector(shifted_points[i], shifted_points, 1.5)
            # print(mean_shift_vector-shifted_points[i])
            shift_distance = np.linalg.norm(mean_shift_vector-shifted_points[i]) #norm gives ecludian norm of vector, it can also calcuate ecludian dist bet two points or vectors
            # print(shift_distance)
            new_points[i] = mean_shift_vector
            max_shift = max(max_shift, shift_distance)
        # print("max_shift ",max_shift)
        
        shifted_points = new_points
        print(shifted_points)
        
        if max_shift < tolerance:
            print(f"Converged after {iteration + 1} iterations.")
            break
    
    return shifted_points
        
    



In [625]:
print(data)
mean_shift(data)

[[2.50 3.17]
 [2.50 3.17]
 [2.50 3.17]
 [7.50 8.17]
 [7.50 8.17]
 [7.50 8.17]]
[[2.50 3.17]
 [2.50 3.17]
 [2.50 3.17]
 [7.50 8.17]
 [7.50 8.17]
 [7.50 8.17]]
Converged after 2 iterations.


array([[2.50, 3.17],
       [2.50, 3.17],
       [2.50, 3.17],
       [7.50, 8.17],
       [7.50, 8.17],
       [7.50, 8.17]])