In [1]:
import numpy as np

In [10]:
scalar = np.array(32)
scalar
type(scalar)
scalar.shape

()

In [42]:
one_D_arr = np.array([1,1,1,4])
print(one_D_arr)
print(type(one_D_arr))
one_D_arr.shape

[1 1 1 4]
<class 'numpy.ndarray'>


(4,)

In [17]:
print(one_D_arr[-1])
print(one_D_arr[0])

4
1


In [43]:
one_D_arr_2 = np.array([6,7,8,0])
print(one_D_arr + one_D_arr_2) #element wise addition
print(one_D_arr - one_D_arr_2) #element wise subs
print(one_D_arr * one_D_arr_2) #element wise multipication
print(one_D_arr_2 * 2) #scalar mult
print(np.dot(one_D_arr, one_D_arr_2))

[7 8 9 4]
[-5 -6 -7  4]
[6 7 8 0]
[12 14 16  0]
21


In [30]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(type(matrix))
print(matrix)

(2, 3)
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [37]:
print(matrix[0, 1])  # Element in the 1st row, 2nd column
print(matrix[1][1])

2
5


In [45]:
matrix2 = np.array([[5, 6, 7], [8, 9, 1]])
print(matrix + matrix2) #element wise add
print(np.matmul(matrix, matrix2))

[[ 6  8 10]
 [12 14  7]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [49]:
matrix3 = np.array([[5, 6, 7], [8, 9, 1], [1, 2, 3]])
print(matrix.shape, " X ",matrix3.shape)
print(np.dot(matrix, matrix3))
print(np.matmul(matrix, matrix3))

(2, 3)  X  (3, 3)
[[24 30 18]
 [66 81 51]]
[[24 30 18]
 [66 81 51]]


In [55]:
matrix4 = np.matrix_transpose(matrix2)
print(matrix.shape, " X ",matrix4.shape)
print(matrix4)
np.matmul(matrix, matrix4)

(2, 3)  X  (3, 2)
[[5 8]
 [6 9]
 [7 1]]


array([[38, 29],
       [92, 83]])

In [128]:
print(matrix4)
matrix5 = matrix4-1 # substract scalar from each element
print(matrix5)
matrix6 = matrix4 + 1
print(matrix6)
matrix6 = 1 + matrix4
print(matrix6)

[[5 8]
 [6 9]
 [7 1]]
[[4 7]
 [5 8]
 [6 0]]
[[ 6  9]
 [ 7 10]
 [ 8  2]]
[[ 6  9]
 [ 7 10]
 [ 8  2]]


In [61]:
zeros = np.zeros(shape=(3,3), dtype=int)
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [65]:
existing_arr = np.array([[1,2,3], [4,5,6]])
print(existing_arr)
zeros = np.zeros_like(existing_arr, dtype=float) #zeros like will infere the shape from existing arr
print(zeros)

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [67]:
ones = np.ones((2, 4), dtype=int)    # 2x4 matrix filled with ones
print(ones)

[[1 1 1 1]
 [1 1 1 1]]


In [130]:
identity_matrix = np.eye(3) #identity matrix of size 3 X 3
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [135]:
np.arange(start=-10, stop=10, step=1.5) #generate 1 d array from low to high with step

array([-10. ,  -8.5,  -7. ,  -5.5,  -4. ,  -2.5,  -1. ,   0.5,   2. ,
         3.5,   5. ,   6.5,   8. ,   9.5])

In [139]:
arr = np.arange(start=-10, stop=10, step=1.5)
arr.reshape(2,7) #reshape it

array([[-10. ,  -8.5,  -7. ,  -5.5,  -4. ,  -2.5,  -1. ],
       [  0.5,   2. ,   3.5,   5. ,   6.5,   8. ,   9.5]])

In [144]:
lin_space = np.linspace(0, 1, 5) #generate evenly spaced number from the range
print(lin_space)

[0.   0.25 0.5  0.75 1.  ]


In [152]:
mat = np.array([[1,2,3],[4,5,6]])
flattened_matrix = mat.flatten()  #retrun new copy of original arr
reavel_mat = mat.ravel() 
print(reavel_mat)
reavel_mat[0] = 4 # change in ravel will change original array
print(mat)
print(flattened_matrix)

[1 2 3 4 5 6]
[[4 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [121]:
random_array = np.random.rand(3, 3)  # 3x3 matrix with random numbers from 0 to 1
print(random_array)

[[0.73130075 0.34038522 0.0920556 ]
 [0.46349802 0.50869889 0.08846017]
 [0.52803522 0.99215804 0.39503593]]


In [114]:
normal_distribution = np.random.randn(3, 3 )  # 3x3 matrix from standard normal distribution
print(normal_distribution)

[[-1.07004333 -0.18949583  0.25500144]
 [-0.45802699  0.43516349 -0.58359505]
 [ 0.81684707  0.67272081 -0.10441114]]


In [73]:
random_integers = np.random.randint(-19, 10, (3, 3))  # 3x3 matrix with integers from 0 to 9
print(random_integers)

[[ 4 -7  7]
 [-7 -4  6]
 [-5  6  8]]


In [77]:
uniform_distribution = np.random.uniform(-1, 1, (2, 2))  # 2x4 matrix with values from -5 to 5
print(uniform_distribution)

[[ 0.59291467 -0.93261468]
 [-0.91435784  0.14454958]]


In [93]:
array = np.array([10, 20, 30, 40, 50])
random_sample = np.random.choice(array, size=3, replace=False)  # Randomly select 3 unique elements
random_sample_with_replace = np.random.choice(array, size=3, replace=True)  # Randomly select 3 elements you can put back previous elemen to arr
print(random_sample)
print(random_sample_with_replace)

[40 30 10]
[20 40 10]


In [94]:
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)  # Shuffles array in place
print(array)

[5 2 3 1 4]


In [162]:
binomial_distribution = np.random.binomial(n=10, p=0.5, size=50)  # 5 samples from binomial distribution
print(binomial_distribution)

[6 4 6 6 6 5 4 6 7 6 8 8 3 2 3 7 8 4 4 5 4 5 6 5 6 5 1 5 5 5 4 5 5 3 4 7 2
 2 4 5 9 9 9 3 6 5 4 7 4 9]


In [102]:
normal_distribution = np.random.normal(loc=0, scale=3, size=(2,3))  # 2x3 matrix generated which follows normal distribution
print(normal_distribution)

[[ 0.91735931 -0.90002668  2.37431124]
 [ 0.59793077  2.58047851  5.95051031]]


In [112]:
np.random.seed(100)  # Set seed so that you get same rand each time run the code
random_numbers = np.random.rand(2, 2)
print(random_numbers)

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [176]:
np.random.randint(1, 7, 30)

array([1, 5, 5, 6, 1, 5, 3, 6, 2, 4, 5, 1, 4, 6, 6, 6, 4, 1, 2, 6, 2, 4,
       4, 6, 1, 4, 3, 6, 4, 2], dtype=int32)

In [184]:
from scipy.stats import poisson

# Parameters
lambda_rate = 20  # Average rate of visits per hour

# Number of visits to calculate probabilities for
k_values = [15, 20, 25]

# Calculate and print probabilities
for k in k_values:
    probability = poisson.pmf(k, lambda_rate)
    print(f"Probability of exactly {k} visits: {probability:.4f}")


Probability of exactly 15 visits: 0.0516
Probability of exactly 20 visits: 0.0888
Probability of exactly 25 visits: 0.0446
